SCHTASKS/Create /sc minute /mo 2  /tn "讯代理ip" /tr "C:\Users\Administrator\PycharmProjects\proexy\proxey_xundaili.py"
SCHTASKS/Create /sc minute /mo 4  /tn "蘑菇代理ip" /tr "C:\Users\Administrator\PycharmProjects\proexy\proxey_mogudaili.py"
SCHTASKS/Create /sc minute /mo 30  /tn "西刺代理ip" /tr "C:\Users\Administrator\PycharmProjects\proexy\proxey_xici.py"
SCHTASKS/Create /sc minute /mo 20 /tn "快代理代理ip" /tr "C:\Users\Administrator\PycharmProjects\proexy\proxey_kuaidaili.py"
SCHTASKS/Create /sc minute /mo 6  /tn "过滤讯代理ip" /tr "C:\Users\Administrator\PycharmProjects\proexy\fliter.py"
